connectors:
  - type: inbound
    id: rest-connector
    name: Tutorial RestEndpoint Connector
    config:
      type: RestEndpoint
      url: /ingress
      http_method: post
app:
  port: 8080
  host: localhost
  debug: False
  messaging:
    url: "nats://localhost:4222"

logging_config: logging.yaml
