services:
  ## EXTERNAL SERVICES FOR TUTORIAL
  # "external" NATS Jetstream server used for demo exercises
  external-jetstream:
    image: nats:2.8.4-alpine3.15
    volumes:
      - ./resources/external-jetstream:/conf
    command: "--config=/conf/nats-server.conf"
    ports:
      - "4224:4224"
    healthcheck:
      test: ["CMD", "nc", "-zv", "0.0.0.0", "4224"]
      interval: "2s"
      timeout: "5s"
      retries: 3
      start_period: "2s"
    profiles:
      - demo

  # configures the "external" NATS Jetstream server used in the demo
  configure-external-jetstream:
    image: natsio/nats-box:latest
    volumes:
      - ./resources/external-jetstream:/conf
    profiles:
      - demo
    depends_on:
      - external-jetstream
    entrypoint: "nats"
    command: "stream add --server external-jetstream:4224 --config /conf/external-stream.conf"

  # "external" Kafka and Zookeeper servers used in the demo examples
  external-zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    profiles:
      - demo
  external-kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=external-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,INTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://external-kafka:9092,INTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
    healthcheck:
      test: ["CMD", "/opt/bitnami/common/bin/wait-for-port", "9092"]
      start_period: 15s
      interval: 10s
      timeout: 10s
      retries: 4
    depends_on:
      - external-zookeeper
    profiles:
      - demo
    volumes:
      - ./resources/external-kafka:/opt/scripts


  ## HealthOS CORE SERVICES
  # the HealthOS Jetstream instances used for "core" messaging
  healthos-core-jetstream:
    image: nats:2.8.4-alpine3.15
    volumes:
      - ./resources/core-jetstream:/conf
    command: "--config=/conf/nats-server.conf"
    ports:
      - "4222:4222"
    healthcheck:
      test: ["CMD", "nc", "-zv", "0.0.0.0", "4222"]
      interval: "2s"
      timeout: "5s"
      retries: 3
      start_period: "2s"
