version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
loggers:
  linuxforhealth.healthos.core:
    level: DEBUG
  aiokafka:
    level: WARN
  uvicorn:
    level: WARN
