name: HealthOS Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.5"]
        poetry-version: ["1.1.13"]
        module-names: ["core"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install poetry==${{ matrix.poetry-version }}
        cd ${{ matrix.module-names }}/src/linuxforhealth/healthos/${{ matrix.module-names }} && \
          python -m poetry install
    - name: Validate Formatting
      run: |
        cd ${{ matrix.module-names }}/src/linuxforhealth/healthos/${{ matrix.module-names }} && \
          python -m poetry run black ./src ./tests
    - name: Execute Unit Tests
      run: |
        cd ${{ matrix.module-names }}/src/linuxforhealth/healthos/${{ matrix.module-names }} && \
          python -m pytest
